{ :ok , pid } = GenServer.start_link(Sequence.Server, 100, [debug: [:trace, :statistics]])
IO.puts("Returned: #{inspect GenServer.call(pid, :next_number)}")
IO.puts("Returned: #{inspect GenServer.call(pid, :next_number)}")
IO.puts("Returned: #{inspect GenServer.cast(pid, {:increment_number, 150})}")
IO.puts("Returned: #{inspect GenServer.call(pid, :next_number)}")
IO.puts("Returned: #{inspect GenServer.call(pid, :next_number)}")
IO.puts("Returned: #{inspect GenServer.call(pid, {:set_number, 400})}")
IO.puts("Returned: #{inspect GenServer.call(pid, :next_number)}")
IO.puts("Returned: #{inspect GenServer.call(pid, :next_number)}")
IO.puts(inspect (:sys.statistics pid, :get))
